### ISSUE TITLE
Alert: Cast to ObjectId

### ISSUE THREAD

**Issue by EGDPG** [Wellenline/auddly-server#13]
After newest commit, the android app says 
{
Cast to ObjectId failed for the value "undefined" at path "artist" for model "album"
}

Is this due to my folder structure?

**Comment by MihkelBaranov** [comment]
Hard to tell, try removing the API and mongo containers and rebuilding

**Comment by MihkelBaranov** [comment]
Also, make sure your audio files are correctly tagged

**Comment by EGDPG** [comment]
what are all the file extensions that it can play? I restarted a new library all with the extension mp3
would that be the issue? I will try a flac file next.

**Comment by EGDPG** [comment]
I tried both of your suggestions, with the same result.

In the app, I can go to My Music and all my tracks show up with proper album art, track names, and they all play fine. 
However Artists dont show up and when I tap where one should show up onscreen, it produces the error above.
If I tap the album square, it force closes the app.

**Comment by EGDPG** [comment]
Is there a strict folder structure I need to follow? I have used beets to tag all my music with as much detail as possible but it still produces the same error. Thanks

**Comment by MihkelBaranov** [comment]
Folder structure shouldn't matter... Is there any way you could share the library so I can debug it?

**Comment by EGDPG** [comment]
Sorry I haven't commented back yet. I may have solved it, might not be the whole issue but the culprit was the android app itself. I was on the normal app, once I joined the beta and used the new rewritten app, all works fine now.
