### ISSUE TITLE
Official Docker Image?

### ISSUE THREAD

**Issue by NoLooseEnds** [Wellenline/auddly-server#19]
Any plans to make an offical docker image on Docker Hub?

**Comment by MihkelBaranov** [comment]
It's available now!
https://hub.docker.com/r/wellenline/waveline-server 

I'll update the readme at some point, but the basic gist is that it takes the same env variables as the compose file

**Comment by NoLooseEnds** [comment]
Thanks! 

You should make a tag that is "latest" – now you need to specify the version you pull down.
`Pulling waveline (wellenline/waveline-server:)...
ERROR: manifest for wellenline/waveline-server:latest not found`

And also look into a auto build setup, I think that is how most do it. :)

**Comment by NoLooseEnds** [comment]
Latest tag is there now, thanks! :)
