### ISSUE TITLE
Set up IRC/Discord/Gitter/Matrix server for communication or support

### ISSUE THREAD

**Issue by flying-sausages** [Wellenline/auddly-server#29]
I think it is important for ambitious projects like these to build a community soon in order to gather feedback and ge a feeling for what users are stuggling with, as well as meeting potential contributors.

What I've seen done before which hits most people's spots is a Discord server, with a bridged connection to an IRC room on Freenode for the support channel.

**Comment by MihkelBaranov** [comment]
Good idea, feel free to join

https://discord.gg/hCeTmk

**Comment by flying-sausages** [comment]
Might be nice to flaunt on the README and maybe the website as well!

**Comment by kolmone** [comment]
The invite is already invalid, you will need to generate one that lasts longer than Discord's default 24 hours.

**Comment by flying-sausages** [comment]
This one is unlimited never expiring https://discord.gg/mJQm8SJ
