### ISSUE TITLE
Improve database setup documentation/add sqlite option

### ISSUE THREAD

**Issue by flying-sausages** [Wellenline/auddly-server#31]
Setting up Mongo from source is quite cumbersome as there are isn't even a mention that mongo is a dependency. It would be nice to have more detailed steps/links for the initial setup.

Alternatively, as I feel Mongo is a bit of a large dependency for a single-user application, an option to use sqlite would be very appreciated. This would simplify the setup as well as decrease the dependency.

**Comment by MihkelBaranov** [comment]
I'm actually in the process of moving from mongo to PostgreSQL and I'm sure I can add in SQLite support
