### ISSUE TITLE
Server not accessible when port is not exposed on internet

### ISSUE THREAD

**Issue by jakoblover** [Wellenline/auddly-server#32]
- I have built the web app and it is being served up by nginx.
- The docker container running the server is only exposed to localhost:5000 by blocking all other connections in IP tables.

The container waveline-api crashes when I try to connect the webapp to localhost:5000. This also happens if I put the waveline server behind a reverse proxy and try to reach it from the waveline web app on waveline.app

**Comment by MihkelBaranov** [comment]
Can you share some logs from the server crash?

Also can you access http://localhost:5000/system/info?

**Comment by jakoblover** [comment]
For reference if other struggle with this, after talking to Mihkel, the API is completely independent, and the web players access the API from the outside. So you cannot connect to localhost:5000 in the web player if your iptables block this port. 

I just set up another reverse proxy for the API, and it's working great now.
